import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "server"))
import ClapProcessor
import torch
import json

prompts = [
    "music with drums, synth and string",
    "music with funky bassline, groovy drums, and brass section",
    "music with acoustic drums, acoustic bass, and jazzy piano",
    "music with classical strings, grand piano, and orchestral percussion",
    "music with reggae rhythm, ska guitar, and island vibes",
    "music with Latin percussion, salsa piano, and vibrant horns",
    "music with lo-fi beats, chillhop vibes, and smooth melodies",
    "music with retro synthwave, nostalgic melodies, and pulsating basslines",
    "music with folk acoustic guitar, heartfelt lyrics, and warm vocals",
    "music with Celtic fiddle, tin whistle, and traditional Irish tunes",
    "music with electronic dance beats, pulsating synths, and catchy hooks",
    "music with rock guitars, pounding drums, and anthemic choruses",
    "music with ambient textures, spacey synthesizers, and floating melodies",
    "music with trap hi-hats, booming 808s, and atmospheric pads",
    "music with bluesy guitar licks, soulful vocals, and driving rhythm section",
    "music with EDM drops, energetic build-ups, and festival-ready vibes",
    "music with bossa nova rhythm, smooth jazz chords, and sultry saxophone",
    "music with gospel choir, uplifting piano, and inspirational lyrics",
    "music with funky bassline, groovy drums, and brass section",
    "music with dreamy pads, ethereal vocals, and electronic beats",
    "music with acoustic drums, acoustic bass, and jazzy piano",
    "music with driving electric guitar, energetic drums, and powerful vocals",
    "music with classical strings, grand piano, and orchestral percussion",
    "music with epic choir, cinematic brass, and majestic orchestration",
    "music with reggae rhythm, ska guitar, and island vibes",
    "music with Latin percussion, salsa piano, and vibrant horns",
    "music with lo-fi beats, chillhop vibes, and smooth melodies",
    "music with retro synthwave, nostalgic melodies, and pulsating basslines",
    "music with folk acoustic guitar, heartfelt lyrics, and warm vocals",
    "music with Celtic fiddle, tin whistle, and traditional Irish tunes",
    "music with futuristic synths, glitchy effects, and electronic beats",
    "music with heavy metal guitar riffs, pounding drums, and aggressive vocals",
    "music with Bollywood-inspired melodies, tabla rhythms, and sitar solos",
    "music with Japanese koto, taiko drums, and traditional shamisen",
    "music with ambient textures, spacey sounds, and ethereal voices",
    "music with EDM drops, intense build-ups, and pulsating bass",
    "music with bluesy guitar licks, soulful vocals, and smoky atmosphere",
    "music with bossa nova rhythm, smooth jazz chords, and mellow saxophone",
    "music with flamenco guitar, passionate vocals, and rhythmic claps",
    "music with electronic dance beats, catchy hooks, and infectious energy",
    "music with African djembe, kalimba melodies, and tribal chants",
    "music with Caribbean steel drums, calypso rhythm, and tropical vibes",
    "music with 8-bit chiptune sounds, nostalgic melodies, and retro gaming vibes",
    "music with haunting choir, eerie atmospheres, and dark ambient textures",
    "music with Indian classical sitar, tabla rhythms, and raga scales",
    "music with Spanish flamenco guitar, passionate vocals, and fiery rhythms",
    "music with futuristic synth arpeggios, pulsating basslines, and robotic vocals",
    "music with traditional Chinese erhu, guzheng, and bamboo flute",
    "music with retro funk bassline, wah-wah guitar, and groovy horns",
    "music with epic orchestral strings, bombastic percussion, and heroic themes",
    "music with Irish bodhran, fiddle tunes, and Celtic reels",
    "music with Caribbean steel pans, soca rhythm, and island vibes",
    "music with hip-hop beats, rap verses, and urban storytelling",
    "music with Brazilian samba percussion, bossa nova chords, and Latin flair",
    "music with EDM festival drops, anthemic melodies, and euphoric energy",
    "music with Middle Eastern oud, darbuka rhythms, and mystical melodies",
    "music with African highlife guitar, Afrobeat rhythm, and joyful vocals",
    "music with classical piano sonatas, virtuosic performances, and romantic themes",
    "music with heavy dubstep bass drops, wobbly synths, and aggressive energy",
    "music with smooth R&B vocals, sultry melodies, and romantic vibes",
    "music with Russian balalaika, accordion, and folk melodies",
    "music with EDM trap beats, 808 bass, and catchy hooks",
    "music with bluegrass banjo, fiddle tunes, and Appalachian folk",
    "music with electronic ambient textures, atmospheric pads, and minimalistic beats",
    "music with Spanish guitar, flamenco rhythms, and passionate vocals",
    "music with futuristic synthwave, retro-futuristic vibes, and cyberpunk aesthetics",
    "music with Bollywood dance beats, energetic rhythms, and colorful melodies",
    "music with jazz fusion improvisations, complex harmonies, and virtuosic solos",
    "music with African kalimba, mbira melodies, and tribal chants",
    "music with EDM future bass drops, melodic hooks, and uplifting energy",
    "music with Irish tin whistle, bodhran rhythm, and Celtic ballads",
    "music with traditional Japanese shamisen, koto, and taiko drums",
    "music with EDM progressive house beats, euphoric melodies, and anthemic builds",
    "music with classical symphony orchestra, grandiose arrangements, and majestic themes",
    "music with Brazilian bossa nova guitar, smooth vocals, and relaxed vibes",
    "music with EDM hardstyle drops, aggressive basslines, and pounding kicks",
    "music with French accordion, gypsy jazz guitar, and Parisian charm",
    "music with 80s synth-pop vibes, retro drum machines, and nostalgic melodies",
    "music with African marimba, mbira, and traditional percussion",
    "music with EDM tropical house beats, steel drums, and summery vibes",
    "music with Indian tabla percussion, sitar melodies, and raga scales",
    "music with EDM dubstep drops, aggressive wobbles, and intense energy",
    "music with Italian mandolin, accordion, and romantic serenades",
    "music with EDM trance beats, euphoric melodies, and uplifting synths",
    "music with Chinese guzheng, pipa, and traditional folk melodies",
    "music with EDM drum and bass drops, energetic rhythms, and rolling basslines",
    "music with Scottish bagpipes, Highland drums, and patriotic anthems",
    "music with EDM glitch hop beats, funky grooves, and glitchy effects",
    "music with Turkish saz, darbuka rhythms, and Anatolian melodies",
    "music with EDM psytrance drops, hypnotic basslines, and psychedelic sounds",
    "music with Hawaiian ukulele, tropical steel guitar, and island melodies",
    "music with EDM house beats, catchy vocal chops, and dancefloor energy",
    "music with Native American flute, tribal drums, and spiritual chants",
    "music with EDM electro swing beats, vintage samples, and swingin' rhythms",
    "music with Spanish flamenco guitar, castanets, and passionate vocals",
    "music with EDM synthpop beats, catchy hooks, and infectious melodies",
    "music with Caribbean steel pans, reggae rhythm, and laid-back vibes",
    "music with EDM trap beats, dark synths, and aggressive energy",
    "music with Irish Celtic harp, bodhran rhythm, and enchanting melodies",
    "music with EDM future bass drops, emotional chords, and uplifting vibes",
    "music with Japanese koto, shakuhachi flute, and traditional melodies",
    "music with EDM progressive trance beats, euphoric synths, and epic builds",
    "music with Brazilian samba percussion, bossa nova guitar, and Latin flair",
    "music with EDM big room house drops, festival vibes, and massive energy",
    "music with African kalimba, mbira, and tribal rhythms",
    "music with EDM drumstep beats, aggressive basslines, and halftime grooves",
    "music with Indian classical sitar, tabla percussion, and raga scales",
    "music with EDM chillout beats, relaxing melodies, and serene atmospheres",
    "music with Spanish flamenco guitar, castanets, and passionate vocals",
    "music with EDM hard trance beats, driving basslines, and intense energy",
    "music with African mbira, kalimba, and rhythmic chants",
    "music with EDM future bass drops, melodic hooks, and dreamy atmospheres",
    "music with Scottish bagpipes, Highland drums, and patriotic melodies",
    "music with EDM glitch hop beats, funky grooves, and glitchy effects",
    "music with Russian balalaika, accordion, and folk melodies",
    "music with EDM psytrance drops, psychedelic sounds, and hypnotic rhythms",
    "music with Italian mandolin, accordion, and romantic melodies",
    "music with EDM dubstep beats, aggressive wobbles, and intense energy",
    "music with Caribbean steel drums, calypso rhythm, and tropical vibes",
    "music with EDM house beats, catchy vocal chops, and dancefloor energy",
    "music with Chinese guzheng, pipa, and traditional melodies",
    "music with EDM drum and bass drops, energetic rhythms, and rolling basslines",
    "music with Irish tin whistle, bodhran rhythm, and Celtic melodies",
    "music with EDM trance beats, euphoric melodies, and uplifting synths",
    "music with Turkish oud, darbuka percussion, and Middle Eastern melodies",
    "music with EDM synthwave beats, retro vibes, and nostalgic melodies",
    "music with Indian tabla percussion, sitar melodies, and classical raga",
    "music with EDM hardstyle beats, aggressive synths, and pounding kicks",
    "music with French accordion, gypsy jazz guitar, and Parisian charm",
    "music with EDM tropical house beats, steel drums, and summery vibes",
    "music with a serene beach ambiance, gentle waves, and seagull calls",
    "music with a bustling cityscape background, urban noises, and street chatter",
    "music with a tranquil forest atmosphere, bird songs, and rustling leaves",
    "music with a futuristic sci-fi setting, electronic hums, and spacey echoes",
    "music with a cozy fireside mood, crackling flames, and warm acoustic tones",
    "music with a mystical enchanted forest vibe, ethereal whispers, and magical sounds",
    "music with a romantic candlelit ambiance, soft piano melodies, and intimate whispers",
    "music with a haunted mansion atmosphere, eerie creaks, and ghostly echoes",
    "music with a lively carnival scene, festive cheers, and carnival ride sounds",
    "music with a tranquil mountain landscape, echoing winds, and distant bird calls",
    "music with a futuristic cyberpunk cityscape, neon lights, and bustling crowds",
    "music with a mystical underwater realm, bubbling water, and mysterious echoes",
    "music with a serene garden setting, trickling fountains, and chirping crickets",
    "music with a chaotic battlefield ambiance, war drums, and distant battle cries",
    "music with a cozy café atmosphere, murmuring conversations, and clinking cups",
    "music with a celestial cosmic backdrop, twinkling stars, and ethereal echoes",
    "music with a bustling market ambiance, vendors' calls, and lively chatter",
    "music with a spooky haunted graveyard atmosphere, eerie howls, and ghostly whispers",
    "music with a serene lakeside setting, gentle ripples, and distant bird songs",
    "music with a dramatic thunderstorm backdrop, rumbling thunder, and pouring rain",
    "music with a vibrant festival atmosphere, upbeat music, and cheering crowds",
    "music with a serene starry night sky, twinkling constellations, and peaceful silence",
    "music with a bustling office environment, typing keyboards, and ringing phones",
    "music with a mysterious ancient temple ambiance, echoing corridors, and hidden whispers",
    "music with a lively street market scene, vendors' calls, and bustling activity",
    "music with a tranquil desert oasis atmosphere, gentle breezes, and distant camel bells",
    "music with a cozy winter cabin ambiance, crackling fireplace, and snowy winds",
    "music with a haunted asylum setting, echoing footsteps, and distant screams",
    "music with a festive holiday celebration, jingling bells, and cheerful laughter",
    "music with a mysterious alien world ambiance, strange creatures, and eerie echoes",
    "music with a bustling train station atmosphere, whistling trains, and passenger chatter",
    "music with a tranquil bamboo forest scene, rustling bamboo, and chirping crickets",
    "music with a vibrant street parade ambiance, marching bands, and colorful floats",
    "music with a tranquil cherry blossom garden, gentle breeze, and falling petals",
    "music with a busy airport terminal atmosphere, PA announcements, and bustling crowds",
    "music with a mysterious lost temple setting, echoing chambers, and hidden treasures",
    "music with a lively sports stadium ambiance, cheering crowds, and referee whistles",
    "music with a tranquil mountain peak scene, echoing winds, and majestic vistas",
    "music with a bustling seaside boardwalk, carnival games, and seagull cries",
    "music with a haunted shipwreck ambiance, creaking wood, and ghostly whispers",
    "music with a serene beach ambiance, gentle waves, seagull calls, and xylophone melodies",
    "music with a bustling cityscape background, urban noises, street chatter, and glockenspiel accents",
    "music with a tranquil forest atmosphere, bird songs, rustling leaves, and kalimba melodies",
    "music with a futuristic sci-fi setting, electronic hums, spacey echoes, and steel drum rhythms",
    "music with a cozy fireside mood, crackling flames, warm acoustic tones, and marimba accents",
    "music with a mystical enchanted forest vibe, ethereal whispers, magical sounds, and handpan melodies",
    "music with a romantic candlelit ambiance, soft piano melodies, intimate whispers, and celesta accents",
    "music with a haunted mansion atmosphere, eerie creaks, ghostly echoes, and musical saw harmonies",
    "music with a lively carnival scene, festive cheers, carnival ride sounds, and vibraphone melodies",
    "music with a tranquil mountain landscape, echoing winds, distant bird calls, and hang drum rhythms",
    "music with a futuristic cyberpunk cityscape, neon lights, bustling crowds, and melodica harmonies",
    "music with a mystical underwater realm, bubbling water, mysterious echoes, and steel tongue drum melodies",
    "music with a serene garden setting, trickling fountains, chirping crickets, and dulcimer melodies",
    "music with a chaotic battlefield ambiance, war drums, distant battle cries, and rainstick effects",
    "music with a cozy café atmosphere, murmuring conversations, clinking cups, and kalimba solos",
    "music with a celestial cosmic backdrop, twinkling stars, ethereal echoes, and jaw harp rhythms",
    "music with a bustling market ambiance, vendors' calls, lively chatter, and tongue drum accents",
    "music with a spooky haunted graveyard atmosphere, eerie howls, ghostly whispers, and glass harp harmonies",
    "music with a serene lakeside setting, gentle ripples, distant bird songs, and rainstick effects",
    "music with a dramatic thunderstorm backdrop, rumbling thunder, pouring rain, and bell tree accents",
    "music with a vibrant festival atmosphere, upbeat music, cheering crowds, and steel pan melodies",
    "music with a serene starry night sky, twinkling constellations, peaceful silence, and melodica solos",
    "music with a bustling office environment, typing keyboards, ringing phones, and thumb piano accents",
    "music with a mysterious ancient temple ambiance, echoing corridors, hidden whispers, and bamboo flute melodies",
    "music with a lively street market scene, vendors' calls, bustling activity, and rainstick effects",
    "music with a tranquil desert oasis atmosphere, gentle breezes, distant camel bells, and hang drum rhythms",
    "music with a cozy winter cabin ambiance, crackling fireplace, snowy winds, and celesta accents",
    "music with a haunted asylum setting, echoing footsteps, distant screams, and musical saw harmonies",
    "music with a festive holiday celebration, jingling bells, cheerful laughter, and vibraphone melodies",
    "music with a mysterious alien world ambiance, strange creatures, eerie echoes, and jaw harp rhythms",
    "music with a bustling train station atmosphere, whistling trains, passenger chatter, and kalimba accents",
    "music with a tranquil bamboo forest scene, rustling bamboo, chirping crickets, and steel tongue drum rhythms",
    "music with a vibrant street parade ambiance, marching bands, colorful floats, and glockenspiel accents",
    "music with a tranquil cherry blossom garden, gentle breeze, falling petals, and kalimba melodies",
    "music with a busy airport terminal atmosphere, PA announcements, bustling crowds, and xylophone solos",
    "music with a mysterious lost temple setting, echoing chambers, hidden treasures, and glass harp harmonies",
    "music with a lively sports stadium ambiance, cheering crowds, referee whistles, and steel pan melodies",
    "music with a tranquil mountain peak scene, echoing winds, majestic vistas, and thumb piano accents",
    "music with a bustling seaside boardwalk, carnival games, seagull cries, and vibraphone melodies",
    "music with a haunted shipwreck ambiance, creaking wood, and ghostly whispers"]

device = "cpu"
processor_clap = ClapProcessor.ClapProcessor(device=device)
vecs = processor_clap.processText(prompts)

def find_nearest_vector(input_vector, k=20):
    distances = torch.norm(vecs - input_vector, dim=1)
    nearest_indices = torch.argsort(distances)[:k]
    return vecs[nearest_indices], nearest_indices

def traverse_folders(root_folder):
    for root, dirs, files in os.walk(root_folder):
        for file in files:
            file_path = os.path.join(root, file)
            if file_path.endswith(".pt"):
                yield file_path

prompt_datas = []
for oripath in traverse_folders('/export/data/clap/encode/audio/cb/'):
    data = torch.load(oripath)
    path = oripath.split('/')[-1].split("_")[0]
    embed = data["full"].view(-1)
    nearest_vector, indexes = find_nearest_vector(embed)
    audio_prompt = []
    for index in indexes:
        audio_prompt.append(prompts[index])
    prompt_datas.append({
        "songid": path,
        "prompts": audio_prompt
    })

with open("cb_audio_prompt.json", 'w') as json_file:
    json.dump(prompt_datas, json_file, indent=4)