from Code_for_Experiment.Targeted_Training.sit_prompt_finetuning.music_dit2.modules.embeddings.rotary_pos_embedding import RotaryPosEmbedding
import torch
import RotaryPosEmbedding
import SinusoidalPositionalEmbedding
import LinearEmbedding