mq:
  END_POINT : "https://oss-cn-zhangjiakou.aliyuncs.com"  # OSS 外网节点
  ACCESS_KEY_ID : "LTAI5tKhVqkUUDmSYuQoBGiT"
  ACCESS_KEY_SECRET : "9L3YRpWX9AH31MnzeVOY2QSSfIy2eD"
  BUCKET_NAME : "ama-prof-divi-source"  # 你的 bucket 名称

  MQCP_HOST : 'rabbitmq-serverless-cn-jeo3og3a00f.cn-zhangjiakou.amqp-2.net.mq.amqp.aliyuncs.com'
  MQCP_PORT : 5672
  MQCP_VHOST : 'ama-prof-divi'
  MQCP_USER : 'MjpyYWJiaXRtcS1zZXJ2ZXJsZXNzLWNuLWplbzNvZzNhMDBmOkxUQUk1dFFtZnVnOFJKUlV2aTdmUE5XZw=='
  MQCP_PASS : 'RUY1NTQ2NUM3MDc0RUVBRERGOTEzQkI3RUNCNjZDOTYyODlGQkQ4NDoxNzExOTg1ODA3Mjk5'
  
  # Queue Names to your service
  SUBQ_NAME : 'create_music_03_soundtrack'
  PUBQ_NAME : 'create_music_03_soundtrack_resp'

oss:
  host : "https://ama-prof-divi-source.oss-cn-zhangjiakou.aliyuncs.com"

suno:
  apikey : "D8hipvvHRv10tLC+9Wgh126NkmKM5ILZ"
  # model : "chirp-v3-5"
  model : "chirp-v3-0"
  num_work : 10

dewatermark:
  use_encodec_dewatermark: False
  device_list : [0,1,2,3]
