mq:
  END_POINT : ""  # OSS 外网节点
  ACCESS_KEY_ID : ""
  ACCESS_KEY_SECRET : ""
  BUCKET_NAME : "ama-prof-divi-source"  # 你的 bucket 名称

  MQCP_HOST : ''
  MQCP_PORT : 5672
  MQCP_VHOST : 'ama-prof-divi'
  MQCP_USER : ''
  MQCP_PASS : ''
  
  # Queue Names to your service
  SUBQ_NAME : 'create_music_03_soundtrack'
  PUBQ_NAME : 'create_music_03_soundtrack_resp'

oss:
  host : ""

suno:
  apikey : ""
  # model : "chirp-v3-5"
  model : "chirp-v3-0"
  num_work : 10

dewatermark:
  use_encodec_dewatermark: False
  device_list : [0,1,2,3]
