from .specloss import MultiScaleMelSpectrogramLoss
from .stftloss import MRSTFTLoss
from Code_for_Experiment.Targeted_Training.dit_training_on_hifigan_vae.music_dit.modules.vae.training.losses.sisnrloss import SISNRLoss
from .adversarial_loss import AdversarialLoss, get_adversarial_loss