vae:
  sampling_rate: 24000
  num_channels: 2
  chunk_stride: 245760
  chunk_length: 262144
  dim: 64
  num_filters: 4
  upsampling_ratios: [ 4, 4, 4, 2, 2, 2, 2, 2 ]
  upsampling_kernel_sizes: [ 8, 8, 8, 4, 4, 4, 4, 4 ]
  resblock_kernel_sizes: [ 3, 5, 7 ]
  resblock_dilation_sizes: [ [1, 3, 5], [1, 3, 5], [1, 3, 5] ]
  initial_kernel_size: 3
  last_kernel_size: 15
  activation: "LeakyReLU"
  activation_params:
    negative_slope: 0.1
  final_activation: "Tanh"
  norm_type: "BatchNorm1d"
  norm_params:
  num_lstm_layers: 0
  padding_mode: "reflect"
