from .label_embedding import LabelEmbedding
from .rotary_pos_embedding import RotaryPosEmbedding
from Code_for_Experiment.Targeted_Training.dit_training_on_vae.music_dit2.modules.embeddings.sinusoidal_pos_embedding import SinusoidalPosEmbedding