tiktoken:
  pretrained_model: "cl100k_base"
  special_tokens:
    - '<|ss_start|>'
    - '<|ss_end|>'
    - '<|ss_sep|>'
    - '<|ss_pad|>'
    - '<|ss_unk|>'
    - '<|ss_mask|>'
    - '<|ss_verse|>'
    - '<|ss_chorus|>'
    - '<|ss_bridge|>'
    - '<|ss_prechorus|>'
    - '<|ss_intro|>'
    - '<|ss_outro|>'
    - '<|ss_interlude|>'
    - '<|ss_instrumental|>'
    - '<|ss_solo|>'
    - '<|ss_hook|>'
    - '<|ss_refrain|>'
    - '<|ss_coda|>'
    - '<|ss_postchorus|>'
    - '<|ss_prelude|>'
    - '<|ss_stanza|>'
    - '<|vo_ap|>'
    - '<|vo_sp|>'
