training:
  preprocessing:
    segment_length_min: 20
    segment_length_max: 30
    prompt_length: 20
    max_split_batches: 100
  vae:
    random_seed: 666
    dataloader_num_workers: 4
    use_data_files_proportion: 1.0
    training_dataset_proportion: 0.9
    num_epochs: 10
    num_validation_steps: 0
    warmup_steps_without_discriminator: 20000
    checkpoint_dir: "/nfs/home/carl/data/outputs/music-dit/checkpoints"
    log_dir: "/nfs/home/carl/data/outputs/music-dit/logs"
